<?php

namespace Spatie\Activitylog;

use Illuminate\Foundation\Support\Providers\EventServiceProvider as ServiceProvider;
use Spatie\Activitylog\Events\ActivityEvents;
use Spatie\Activitylog\Listeners\ActivityListener;

class ActivityEventProvider extends ServiceProvider
{
    protected $listen = [
        ActivityEvents::class => [
            ActivityListener::class,
        ]
    ];

    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }
}
